services:
    php_aws_secrets_app:
        container_name: php_aws_secrets_app
        build:
            args:
                PROJECTINIT_UID: ${PROJECTINIT_UID}
                PROJECTINIT_GID: ${PROJECTINIT_GID}
            context: ./
            dockerfile: Dockerfile
        image: php_aws_secrets_app
        restart: "unless-stopped"
        ports:
            - "13080:8080"
        volumes:
            - ./:/usr/src/app
            - ./projectinit_docker/dev/php/usr/local/etc/php/conf.d/zz_php.ini:/usr/local/etc/php/conf.d/zz_php.ini
