#!/usr/bin/env bash

set -e
source ./projectinit_docker/cli/docker/docker_cli.sh

help() {
  echo "ProjectInit.sh Project CLI"
  echo "Generated by ProjectInit.sh Version:0.5.1-alpha"
  echo "----------"
  echo ""
  echo "Overview of features:"
    echo "docker_compose_up - Start containers using Docker Compose"
  echo "docker_compose_build - Build containers using Docker Compose"
}

main() {
  if [[ -z "$1" ]]; then
    echo "No feature selected. Nothing is executed."
    echo "Run 'sh projectinit_cli.sh help' to see the list of available features."
    exit
  fi

  if declare -f "$1" > /dev/null; then
    "$@"
  else
    echo "You have asked for invalid feature: $1"
    exit 2
  fi
}

main "$@"