= AWS credentials and authentication
:toc:
:toclevels:5

== Local development environment (bare metal)

AWS CLI is only needed if you intend to use your AWS `profile` to configure the bundle and authenticate. It is not needed
if you are using long-terms Access Keys or AWS STS tokens.

https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html[Official AWS CLI installation guide]

Short version:

* Download AWS CLI
* Run
+
[source]
----
aws configure
----
+
to create your profile. Use the profile name in this bundle's configuration
(`config/packages/symfony8_aws_secretd.yaml`).

== Local development environment (Docker)

This repository is developed and maintained in a dockerized development environment. The container does not have AWS CLI
installed, because it's using AWS STS tokens for authentication during development and testing.

If you are running a dockerized application and intend to use profiles for authentication, there are a couple of
options:

* Install AWS CLI on your host. Create a bind mount and load `~/.aws` directory inside your container.
* Consult documentation of your container's operating system on how to install AWS CLI inside your container.

== AWS EC2 instance

EC2 instances should already have all the necessary connections to other AWS services preconfigured. If you are running
a Symfony application which uses this bundle on an EC2 instance, you probably don't need to configure anything.

If you are encountering issues, check if roles and permissions of your IAM user are set up correctly.

== AWS CodeBuild and Docker containers

Add `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` environment variable value into your Docker container in the build step.
To do that, modify your `buildspec.yml` file:

.buildspec.yaml
[source,yaml]
----
phases:
    build:
        commands:
            docker build --build-arg AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI -t myapp:latest .
----

Then add it as an argument in your `Dockerfile`:

.Dockerfile
[source,dockerfile]
----
ARG AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
----

That's it! AWS SDK will handle the rest. The app in your Docker container can now connect to AWS services (including
Secrets Manager) by using AWS metadata service to retrieve credentials from an IAM role.

== Links

* link:../README.adoc[Home]