= Local development
:toc:
:toclevels: 5

== Introduction

This is a guide for setting up development environment for developing
`constup-foss/symfony-aws-secrets-bundle` library.

== Setting up AWS for local development

[IMPORTANT]
====
**This guide assumes that you are developing locally on a standalone AWS account. If you are using your organization's
account for development purposes, consult your organization's documentation for instructions.**
====

This guide is a short, direct, bullet-point version of the official documentation for
link:https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/getting-started_index.html[AWS SDK for PHP Version 3].
It assumes that you only have your own standalone AWS account created with nothing else set up in it. You are free to
skip steps that you've already covered.

=== AWS Authentication

Starting AWS article: https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/credentials.html[Authenticating with
AWS using AWS SDK for PHP Version 3]

Steps:

* Enable IAM Identity Center
** Open the https://console.aws.amazon.com/singlesignon[IAM Identity Center console]
** Enable IAM Identity Center for an *account instance*. It's a single button click to enable it.
*** More details on the account instances:
https://docs.aws.amazon.com/singlesignon/latest/userguide/account-instances-identity-center.html
** Complete article: https://docs.aws.amazon.com/singlesignon/latest/userguide/enable-identity-center.html
* Create an IAM user group
** Go to **`IAM > IAM users and groups`** (https://console.aws.amazon.com/iam/home?#/groups) and create a new IAM user
group
** Attach the following permission policies when creating the group:
*** `AWSSecretsManagerClientReadOnlyAccess`
* Create an IAM user and add it to the group created previously
** Go to **`IAM > IAM users`** (https://console.aws.amazon.com/iam/home?#/groups) and create a new user
*** You do not need __Provide user access to the AWS Management Console__ option selected, since your IAM user will only
be accessing AWS services programmatically.
*** Add the user to the previously created group
* Create AWS access key
** Open the IAM user you've just created and click on **Create access key**
*** On the __Access key best practices & alternatives__ select **Other**. This is just an informative warning page about
the security implications of using access keys.
*** Retrieve your *Access key* and *Secret access key* on one of the next pages and **save them somewhere safe**.

=== Note on AWS CLI

AWS CLI (https://aws.amazon.com/cli/) is not directly needed for development purposes.

